# Site settings
title: Emanuele Paiano
header-img: img/home-bg.jpg
email: nixw0rm@gmail.com
copyright_name: Emanuele Paiano
description: "Coder's homepage"
baseurl: "https://emanuelepaiano.github.io/"
url: "https://emanuelepaiano.github.io"
twitter_username: emanuele_paiano
github_username:  emanuelepaiano
facebook_username:  nito.infi86
#email_username:  nixw0rm@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
