# Site settings
title: Emanuele Paiano
header-img: img/4.jpg
email: 
copyright_name: Emanuele Paiano
description: "Emanuele Paiano projects blog"
baseurl: "https://emanuelepaiano.github.io/"
url: "https://emanuelepaiano.github.io"
twitter_username: emanuele_paiano
github_username:  emanuelepaiano
facebook_username:  nito.infi86


# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-93922602-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
