# Site settings
title: Emanuele Paiano
header-img: img/home-bg.jpg
email: nixw0rm@gmail.com
copyright_name: Emanuele Paiano
description: ""
baseurl: ""
url: "https://emanuelepaiano.github.io"
twitter_username: SBootstrap
github_username:  davidtmiller
facebook_username:  StartBootstrap
email_username:  nixw0rm@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
